.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. crowcoin_qt test_crowcoin_qt
clean: FORCE
	$(MAKE) -C .. crowcoin_qt_clean test_crowcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_crowcoin_qt_check
crowcoin-qt crowcoin-qt.exe: FORCE
	 $(MAKE) -C .. crowcoin_qt
